---
- hosts: kubernetes-server
  become: true
  tasks:
    - name: Copy kubernetes deployment configs
      copy:
        src: ../kubernetes/
        dest: /home/ubuntu/
    - name: Delete running services
      shell: kubectl delete -f tomcat-service.yaml
    - name: Delete running deployments
      shell: kubectl delete -f tomcat-deployment.yaml
    - name: Create tomcat deployment
      shell: kubectl create -f tomcat-deployment.yaml
    - name: Create tomcat service
      shell: kubectl create -f tomcat-service.yaml

